### ISSUE TITLE
Any Idea how to fix the WIFI?

### ISSUE THREAD

**Issue by benja95** [nakixii/android_kernel_xiaomi_sm8350#1]

**Comment by nakixii** [comment]
Inc folders cant be detected, and I have no idea about it.

**Comment by benja95** [comment]
Hi, 
I used the qcacld-3.0 from OnePlus9 with additional patches taken from [https://github.com/kristofpetho/kernel_oneplus_sm8350/commits/omega-11.0](url) 
and WIFI works

**Comment by nakixii** [comment]
Did you fix the speakers?

**Comment by benja95** [comment]
not yet..
