### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by VortexHD** [nakixii/android_kernel_xiaomi_sm8350#2]
Hello, I keep getting this error when building.

FAILED: 
kernel/xiaomi/sm8350/drivers/staging/utils/sigma-dut/Android.mk: error: "sigma_dut (native:platform) can not link against libpcap.vendor (native:vendor)" 
kernel/xiaomi/sm8350/drivers/staging/utils/sigma-dut/Android.mk: error: "sigma_dut (native:platform) can not link against libwifi-hal-qcom (native:vendor)" 
build/make/core/main.mk:950: error: exiting from previous errors.

**Comment by VortexHD** [comment]
If I remove those 2 from Android.mk I get this error instead

[ 55% 134/242] including kernel/xiaomi/sm8350/drivers/staging/utils/sigma-dut/An
fatal: No names found, cannot describe anything.
fatal: No tags can describe '64a768f2addb2b715e81dc49aacecdaaa5ceae71'.
Try --always, or create some tags.

**Comment by nakixii** [comment]
I think this is Xiaomi’s problem, I haven’t modified this part. You should go to MiCode to open an issue.
